services:
  container_1:
    container_name: container_1
    build: 
      context: ./c1
      dockerfile: Dockerfile 
    ports:
      - 6000:6000
    networks:
      - my-network
    volumes:
      - .:/my_files/

  container_2:
    container_name: container_2
    build:
      context: ./c2
      dockerfile: Dockerfile 
    ports:
      - 8080:8080
    networks:
      - my-network
    volumes:
      - .:/my_files/

networks:
  my-network:
    driver: bridge