apiVersion: v1
kind: Service
metadata:
  name: combined-service-1
spec:
  selector:
    app: combined
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: combined-service
spec:
  selector:
    app: combined
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP